### ISSUE TITLE
New status layout idea for Monday

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#452]
![graphic-layout-5](https://cloud.githubusercontent.com/assets/16124816/22345156/f785a102-e3cc-11e6-90a7-db634201c585.png)
![graphic-layout-6](https://cloud.githubusercontent.com/assets/16124816/22345168/06857092-e3cd-11e6-8894-bd8cb84a7147.png)

**Comment by angela-smithers** [comment]
Indicators 1 and 2 show the same layout idea.
Indicator 3 shows another idea; much smaller, harder to read.

**Comment by philipashlock** [comment]
Merging these back into #445
