### ISSUE TITLE
Status indicator - brainstorm

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#460]
![58888907-dial-meter-templates-with-red-need-and-units-set-at-4-stages-levels-generic-indicator-measurement-ic](https://cloud.githubusercontent.com/assets/16124816/22934639/a75d8ee4-f29d-11e6-9915-e8e4d4ed1721.jpg)
![stock-vector-set-of-icons-of-timers-on-a-white-background-green-indicator-eps-used-mesh-gradient-and-211923721](https://cloud.githubusercontent.com/assets/16124816/22934642/a9a53c10-f29d-11e6-8bb3-a8521d2eb3b1.jpg)
![hourgalss](https://cloud.githubusercontent.com/assets/16124816/22934855/8586bbc8-f29e-11e6-8810-1c2210c9b23a.jpg)

**Comment by JenPark9** [comment]
These are good, but connote continuous variables being measured--such as time. We would best have something that connotes ordered categorical variables being measured--such as school grade levels.

Sent from my iPhone

On Feb 14, 2017, at 10:15 AM, Angela <notifications@github.com<mailto:notifications@github.com>> wrote:


[58888907-dial-meter-templates-with-red-need-and-units-set-at-4-stages-levels-generic-indicator-measurement-ic]<https://cloud.githubusercontent.com/assets/16124816/22934639/a75d8ee4-f29d-11e6-9915-e8e4d4ed1721.jpg>
[stock-vector-set-of-icons-of-timers-on-a-white-background-green-indicator-eps-used-mesh-gradient-and-211923721]<https://cloud.githubusercontent.com/assets/16124816/22934642/a9a53c10-f29d-11e6-8bb3-a8521d2eb3b1.jpg>
[hourgalss]<https://cloud.githubusercontent.com/assets/16124816/22934855/8586bbc8-f29e-11e6-8810-1c2210c9b23a.jpg>

-

**Comment by angela-smithers** [comment]
![list_font_awesome svg](https://cloud.githubusercontent.com/assets/16124816/23071001/ec556684-f4fa-11e6-9434-9b9460d5a117.png)
![search_font_awesome svg](https://cloud.githubusercontent.com/assets/16124816/23071000/ec2925c4-f4fa-11e6-82ce-3f3737cea821.png)
![time_font_awesome svg](https://cloud.githubusercontent.com/assets/16124816/23070999/ec252cbc-f4fa-11e6-9ac8-9c3e928d3974.png)

**Comment by angela-smithers** [comment]
![02-24capture](https://cloud.githubusercontent.com/assets/16124816/23321292/d5bfed2e-faac-11e6-9bf4-291331248579.PNG)

**Comment by angela-smithers** [comment]
![02-24capture2](https://cloud.githubusercontent.com/assets/16124816/23321366/34bac4c0-faad-11e6-9954-37d6e982813a.PNG)

**Comment by angela-smithers** [comment]
![02-24capture3](https://cloud.githubusercontent.com/assets/16124816/23321517/e8e257f6-faad-11e6-8c32-e43c3cb50f68.PNG)

**Comment by angela-smithers** [comment]
![indicator-icons](https://cloud.githubusercontent.com/assets/16124816/23518726/6ed0e81c-ff42-11e6-991d-fb6ab398cf43.png)

**Comment by angela-smithers** [comment]
![icons3-march2017-11](https://cloud.githubusercontent.com/assets/16124816/23522135/dbe0417a-ff4f-11e6-97b5-03e6f0326e60.png)

**Comment by JenPark9** [comment]
Angela,
I know you have a lot on your plate, but thought I would just send feedback while I am still in town.
Let's make sure the ellipses with dots (rather than dashes) are on the dashboard page when you ahve a chance. Thanks!
Jen

**Comment by angela-smithers** [comment]
posting an idea from February 13 (2017) in case some use comes of it
![radial dial](https://cloud.githubusercontent.com/assets/16124816/24355271/43d5ffbe-12c3-11e7-8139-c66a8d91f0ad.png)
