### ISSUE TITLE
Design progress for the Sustainability Goals brand / home page

### ISSUE THREAD

**Issue by rtwell** [GSA/sdg-indicators#461]
In order to effectively design the home page, we need to determine the look and feel of the Global Goals. Micah and I plan on specifying the following visual guidelines:

• Font choice
• Color palette 
• Layout recommendations e.g. grids and spacing
• Accessibility guidelines
• Guidelines for consistency in visual components like buttons, form fields, etc 
• A jekyll styleguide

Once the team has settled on a styleguide, it can be used to give a consistent visual style and meets best practices for accessibility for the site. 

Additionally, as we craft the design of the home page, we will ensure that it can be applied on top of the Bootstrap framework that the Sustainability Goals is currently utilizing so we do not create overhead in terms of code implementation. 

We will provide mock-ups for both the styles we recommend as well as how those styles look in the context of the home page.

**Comment by angela-smithers** [comment]
Can we use the visual guide from 18F as a jump-off point? https://standards.usa.gov/

**Comment by rtwell** [comment]
i think we're better off using something more ubiquitous—if we are crafting a forkable template that other nations will be able to use, I think we could make some design decisions that will make this platform more accessible and flexible.  

First, using system fonts would fit those needs—faster load times, predicable display, and robust fonts that have multi-lingual versions. 

For color, I'd rather design a system that felt international first, USA second, than the other way around. Users should know this is an international initiative, but they happen to be looking at the US version. the web design standards are so USA in their colors that i'm not sure that's where to reference a color palette.

**Comment by JenPark9** [comment]
Good input. Do you have particular suggestions for a starting point? Something we could look at?

**Comment by JenPark9** [comment]
Sounds interesting. Do you have something in particular that we could look at as an example?

**Comment by rtwell** [comment]
working on it! it takes a bit of time to put this together on our 2–4 hours
a week budget. we're shooting to have something to share next week!

**Comment by JenPark9** [comment]
Ok, cool. Thanks!

-----Original Message-----
