### ISSUE TITLE
Language translation script

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#462]
**This is our code provided by Google** (of course include the open tag symbol):
```
<div id="google_translate_element"></div>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
```

**Comment by angela-smithers** [comment]
Here are the instructions:
**Paste this code onto your website**

Copy and paste the following code snippets onto every page you want to translate

Do not remove, conceal or alter the Google logo that is presented in websites containing the plugin.

Place this snippet where you'd like to display the Website Translator plugin on your page

**Comment by angela-smithers** [comment]
The only question is: _where do we want it?_
Top-right? Bottom-right?
I can present a mockup and then test it (live)

**Comment by angela-smithers** [comment]
![sdg-capture2](https://cloud.githubusercontent.com/assets/16124816/23473511/7043be32-fe7e-11e6-8745-607f1fb03b7a.png)
![sdg-capture](https://cloud.githubusercontent.com/assets/16124816/23473513/73fdffd8-fe7e-11e6-8b28-9947d25e84d1.png)
Either in the top or bottom. Or maybe both?

**Comment by JenPark9** [comment]
Top right! Wonderful!!!!

**Comment by angela-smithers** [comment]
Hello @philipashlock 
I created the translation for Contact
https://github.com/GSA/sdg-indicators/blob/gh-pages/_translations/contact.md
Did I put it in the right place?

**Comment by angela-smithers** [comment]
I cannot get a zip file of the Spanish icons to attach here.

![es-01](https://user-images.githubusercontent.com/16124816/27489164-91686b16-5807-11e7-9650-104f0812a1b5.png)
![es-02](https://user-images.githubusercontent.com/16124816/27489163-9166dff8-5807-11e7-8d65-34a7d51422ce.png)
![es-03](https://user-images.githubusercontent.com/16124816/27489167-916da522-5807-11e7-95f5-7d485120992f.png)
![es-04](https://user-images.githubusercontent.com/16124816/27489165-91691aa2-5807-11e7-9328-30a68fad8de6.png)
![es-05](https://user-images.githubusercontent.com/16124816/27489162-9166d508-5807-11e7-954c-35cb80583533.png)
![es-06](https://user-images.githubusercontent.com/16124816/27489169-916dd2ea-5807-11e7-9b6d-b0ebe6a63699.png)
![es-07](https://user-images.githubusercontent.com/16124816/27489170-91718b56-5807-11e7-9314-456cafbf1029.png)
![es-08](https://user-images.githubusercontent.com/16124816/27489166-916d596e-5807-11e7-86a6-c57c55200562.png)
![es-09](https://user-images.githubusercontent.com/16124816/27489168-916dc926-5807-11e7-9064-7918ac9b1987.png)
![es-10](https://user-images.githubusercontent.com/16124816/27489171-9172892a-5807-11e7-8d5d-50fee3c7de2c.png)
![es-11](https://user-images.githubusercontent.com/16124816/27489174-917606ae-5807-11e7-94a6-905992e89579.png)
![es-12](https://user-images.githubusercontent.com/16124816/27489172-9172a05e-5807-11e7-87cf-60e0ab375d4f.png)
![es-13](https://user-images.githubusercontent.com/16124816/27489173-917536d4-5807-11e7-8083-ef5956f8b28d.png)
![es-14](https://user-images.githubusercontent.com/16124816/27489175-917681e2-5807-11e7-8d05-a979136f22a7.png)
![es-15](https://user-images.githubusercontent.com/16124816/27489178-917c4442-5807-11e7-918f-30da5a7c1598.png)
![es-16](https://user-images.githubusercontent.com/16124816/27489176-9178db0e-5807-11e7-9f82-16f0e84a906b.png)
![es-17](https://user-images.githubusercontent.com/16124816/27489177-9179a0b6-5807-11e7-92b8-277c13092423.png)

**Comment by angela-smithers** [comment]
I see the translation images were loaded and coded.  Thanks @philipashlock 
![image](https://user-images.githubusercontent.com/16124816/27624342-4bdd43aa-5bae-11e7-87ff-84fc43800833.png)
