### ISSUE TITLE
Great training links

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#463]
**For Github:**
https://www.youtube.com/watch?v=uNa9GOtM6NE
https://www.digitalgov.gov/2014/06/11/the-api-briefing-quick-guide-to-using-github-fdas-openfda-research-project/
https://help.github.com/desktop/guides/getting-started/installing-github-desktop/
**Github for government use:**
https://help.github.com/articles/creating-a-new-organization-from-scratch/

**Comment by angela-smithers** [comment]
**For Jekyll training**
https://www.youtube.com/playlist?list=PLm_Qt4aKpfKijgP0rDH7FSJOlS9IBGbT1

**Comment by angela-smithers** [comment]
1. The UK National Reporting Platform link (copied from the US National Reporting Platform and customized according to their national interests). 
See https://datasciencecampus.github.io/sdg-indicators/.

2. A description of Document System Requirements For the GitHub Website:
https://help.github.com/articles/supported-browsers/
For GitHub Desktop clients
https://help.github.com/desktop/guides/getting-started/installing-github-desktop/#platform-mac
(Windows 7 or later and Mac OS X 10.9 or later) Jekyll requirements:
http://jekyllrb.com/docs/installation/
Prose.io requirements
Might need to research this a bit more - https://github.com/prose/prose Frontend requirements, e.g. U.S. Web Design Standards and Chartist.js https://standards.usa.gov/ https://gionkunz.github.io/chartist-js/index.html#browser-compatibility

3. Some training materials on how to use GitHub (the open source software on which the platform is based) For Github:
https://www.digitalgov.gov/2014/06/11/the-api-briefing-quick-guide-to-using-github-fdas-openfda-research-project/
https://help.github.com/desktop/guides/getting-started/installing-github-desktop/
Github for government use:
https://help.github.com/articles/creating-a-new-organization-from-scratch/

**Comment by JenPark9** [comment]
Thank you, Angela! Beautiful!
