### ISSUE TITLE
Language Library

### ISSUE THREAD

**Issue by JenPark9** [GSA/sdg-indicators#467]
This is the current english version of the spreadsheet that determines the goals and indicator names and other metadata. We'll need another version of this spreadsheet in Spanish to populate them on the site

https://raw.githubusercontent.com/GSA/sdg-indicators/gh-pages/data/sdg_indicator_metadata.csv

**Comment by angela-smithers** [comment]
Hello, team! @Moris-OMB @JenPark9 
Finished the translation for the sdg_goals.csv
[sdg_goals.xlsx](https://github.com/GSA/sdg-indicators/files/1085804/sdg_goals.xlsx)

It has to be converted / GitHub won't let me upload a .csv file

**Comment by angela-smithers** [comment]
And all 242 indicators were translated with the help of Colin 
[sdg_indicator_metadata.xlsx](https://github.com/GSA/sdg-indicators/files/1085810/sdg_indicator_metadata.xlsx)

See column H

**Comment by angela-smithers** [comment]
These could aid in the completion of status.html, goal.html, and indicator.html translations

Not sure if a separate spreadsheet or an additional column was decided upon ...
