### ISSUE TITLE
__ Goal Mockup

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#468]
![graphic layout v4-05](https://cloud.githubusercontent.com/assets/16124816/22889266/7c33c1ec-f1d6-11e6-948b-eaf42287f6d4.jpg)
OLDER VERSION
![sdg-dashboard-v1](https://cloud.githubusercontent.com/assets/16124816/23865897/87702e2e-07ed-11e7-9042-8c7d3e92378a.jpg)

**Comment by angela-smithers** [comment]
http://gsa.github.io/jkan/dashboard/

use col-md-12

remove:
 col-md-3 class

 the entire div with col-md-9

**Comment by JenPark9** [comment]
And I think we will want the icons to the far left of each goal's thermometer.

**Comment by angela-smithers** [comment]
oh - I thought the icons were just for the Indicator status page.  They will be for this Goal status page too?

**Comment by angela-smithers** [comment]
![sdg-dashboard-v2](https://cloud.githubusercontent.com/assets/16124816/23869519/9a82562a-07f9-11e7-9469-46d63c9ad88c.jpg)

**Comment by JenPark9** [comment]
I think so. Does it look good that way?

-----Original Message-----

**Comment by JenPark9** [comment]
[cid:image001.png@01D29C06.BBEA5880][cid:image002.png@01D29C06.BBEA5880][cid:image003.png@01D29C06.BBEA5880]



-----Original Message-----

**Comment by cmterrylynn** [comment]
508 wise, can we ascribe a percentage or adjective if we aren't quantifying the thermometer readings?  The top thermometer has "%%" so if these are reflecting actual percentages, we could just have that reflected in the color line in black and that would address both the blind user and the color blind user who may not be able to see where one color ends and the next begins.  Also, the blue badge probably needs to go a tad darker for the white number to be compliant.  What hex# is the blue?

**Comment by angela-smithers** [comment]
Greetings -

I will inspect the blue to get answer.

**Comment by JenPark9** [comment]
All,
For clarification, the thermometer would show actual percentage in number format. So, for example—but add the percentage sign.

[cid:image001.png@01D29D93.12F44F40]

**Comment by angela-smithers** [comment]
The following is the suggested blue #2773b7
![sdg-dashboard-blue-02](https://cloud.githubusercontent.com/assets/16124816/24110332/8b270138-0d69-11e7-9a33-4ab409bdd368.jpg)

The second image is the blue found in the SDG guideline #0a97d9
![sdg-0a97d9-blue2-02](https://cloud.githubusercontent.com/assets/16124816/24110381/a9f62648-0d69-11e7-9058-ac6022562e0e.jpg)

**Comment by angela-smithers** [comment]
![sdg-goals-bg-withindicators-02](https://cloud.githubusercontent.com/assets/16124816/24113331/d56fff2a-0d72-11e7-9c20-b87c4f64d131.jpg)
a view with indication icons by each goal

**Comment by angela-smithers** [comment]
We can even try another blue from the guideline: #00689D

**Comment by cmterrylynn** [comment]
Perfect!  Comes in at a 6.1:1 ratio where 4.5:1 or higher is compliant.

Terry Lynn (TL) Sales
Section 508 and UI Tester
DHS/CBP/OIT/CSPD
571-468-5271 Desk
703-945-2777 B’Berry

**Comment by JenPark9** [comment]
Hi Angela,
Sorry I wasn't clear. The icons I wanted to put next to the thermometers were not the status icons but hte SDG icons (the blocks for goal 1, 2, etc.). Can you change out?
Thank you!

**Comment by JenPark9** [comment]
Currently where it says Status by Goal change it to Overall Reporting Status.
And right next to the "overall thermometer" please put the SDG wheel icon.
Then, below the overall thermometer, please put Status by Goal.

**Comment by JenPark9** [comment]
And on the Status by Indicator page, can we format the status indication icons without the black disk in the background? So, it would be just the green checkmark, the yellow ellipses, and the red exclamation point? Would that be 508 compliant?

**Comment by angela-smithers** [comment]
![sdg-dashboard-v4](https://cloud.githubusercontent.com/assets/16124816/24154373/5c5448d4-0e27-11e7-8504-9c16f24ad1b5.jpg)

**Comment by JenPark9** [comment]
Awesome! Can we move the sdg wheel to the **left** of the overall reporting thermometer? So that the overall thermometer begins and ends at the same space as the goal specific thermometers?

**Comment by cmterrylynn** [comment]
Would that be repetitive with the Global Goals logo just above it?

**Comment by JenPark9** [comment]
Good point. Is there another icon that refers to the full set of goals?

**Comment by angela-smithers** [comment]
No, the yellow with the white background did not pass accessibility standards. I added color test info in Issue #470 
![sdg-dashboard-v8-03](https://cloud.githubusercontent.com/assets/16124816/24303205/8f37e7b8-108b-11e7-85d4-37717276296c.jpg)

**Comment by JenPark9** [comment]
Thank you, Angela. 
Can we add a bit more white space between "Overall Reporting Status" and the disc icon and thermometer, so the space is about the same as for "Status by Goal" and the goal 1 icon?
Can we use the same format of the goal specific status thermometer for the overall status thermometer --drag out the right side to make all thermometers the same length? And then the overall status thermometer would also have a blue splot with the number 240 inside of it.
Then, we could put an arrow or hover to explain the number in the blue blot refers to the number of global indicators for that dimension.
Thank you, Jennifer

**Comment by cmterrylynn** [comment]
I know I've asked this before, but I'm not sure I asked it right.  The thermometers by each goal, not the top one, are we planning on having percentages on them like the top one?

**Comment by JenPark9** [comment]
Yes, if we can. We would mark percentages and ns (number of indicators in the numerator of that percentage).   We would not put words at the goal level, however.
Alternatively, we could show a ruler referencing percentage if that would be cleaner.                       

-----Original Message-----

**Comment by cmterrylynn** [comment]
Anything textual that a screen reader can read to a blind user or low vision user.

**Comment by JenPark9** [comment]
I am not sure I understand?

Sent from my iPhone

On Mar 24, 2017, at 12:39 PM, Terry LYnn (TL) Sales <notifications@github.com<mailto:notifications@github.com>> wrote:


Anything textual that a screen reader can read to a blind user or low vision user.

-

**Comment by cmterrylynn** [comment]
For accessibility, we need a way for a blind user to get the information that the thermometer is depicting.  A screen reader tool would be able to provide any written content, it just needs the "picture" translated to words/numbers.

**Comment by JenPark9** [comment]
So is there something we should add to enable this?

Sent from my iPhone

On Mar 24, 2017, at 1:51 PM, Terry LYnn (TL) Sales <notifications@github.com<mailto:notifications@github.com>> wrote:


For accessibility, we need a way for a blind user to get the information that the thermometer is depicting. A screen reader tool would be able to provide any written content, it just needs the "picture" translated to words/numbers.

-

**Comment by cmterrylynn** [comment]
If the percentages are labeled, that will do it. The ruler I would need to see.

________________________________

**Comment by JenPark9** [comment]
Ok, good to know.

Sent from my iPhone

On Mar 24, 2017, at 1:58 PM, Terry LYnn (TL) Sales <notifications@github.com<mailto:notifications@github.com>> wrote:

If the percentages are labeled, that will do it. The ruler I would need to see.

________________________________

**Comment by angela-smithers** [comment]
![sdg-dashboard-v9-01](https://cloud.githubusercontent.com/assets/16124816/24313281/99095822-10b2-11e7-87b2-7b32a31f0f9f.jpg)
AND here is a version that someone described earlier.  The description for each goal was on the page 3 times. Here the percentage labels replace each 'long description'.
I have shortened the view of the page because all those colors everywhere look crazy.  The whole thing is so busy; my eyes are screaming!  When you emphasize / colorize everything, then nothing is emphasized.
![sdg-dashboard-v9](https://cloud.githubusercontent.com/assets/16124816/24313433/22750fca-10b3-11e7-8171-8608ee67ccd4.jpg)

**Comment by cmterrylynn** [comment]
Looks good!  Agree, it is mighty colorful :-)

**Comment by JenPark9** [comment]
I think it looks great! If it is too much color, should the thermometer use white/black/grey? What would you recommend?

**Comment by angela-smithers** [comment]
Hello,
Here is a remedy to the excessive use of color. It uses the accordion feature/design suggested in the U.S. Web Design Standards. I could use the alternative icons from the UN Communications material (thus making each and every icon on this page approved for Accessibility). The design is clean, not cluttered.  Plus, there is always room to elaborate within each goal.

![sdg-dashboard-bg-v10](https://cloud.githubusercontent.com/assets/16124816/24364932/441679f8-12e2-11e7-99af-50ac3b40f821.jpg)

**Comment by JenPark9** [comment]
I agree. It looks so much cleaner and better. I really like it!

I also agree that featuring the wheel before overall reporting status was too much. Can we make the overall thermometer in the same format as the goal-specific thermometer?

So we would change
[cid:image001.png@01D2A6F0.C4CE1E10]
To

Overall Reporting Status
[cid:image002.png@01D2A6F0.C4CE1E10]

**Comment by cmterrylynn** [comment]
Looks good!

**Comment by angela-smithers** [comment]
I cannot see the images pasted in Jen's reply (here in Github), so I will check my email ...

**Comment by cmterrylynn** [comment]
Me either.  I was commenting on your latest screen shot.

**Comment by angela-smithers** [comment]
Hello, all.  Most of the main body content is either coded or has a placeholder.   @philipashlock is talking about merging this https://angela-smithers.github.io/jkan/dashboard/ with the main sdg-indicators repository.  That would be good. That way I do not have to recreate the working header (and footer if that will be needed).

Only questions are "how?" and "when?".

**Comment by JenPark9** [comment]
+ Christalyn
Let's schedule a team call w Phil for sometime on Friday. We can see where we are and what we can do.

Sent from my iPhone

On Apr 20, 2017, at 9:27 AM, Angela <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, all. Most of the main body content is either coded or has a placeholder. @philipashlock<https://github.com/philipashlock> is talking about merging this https://angela-smithers.github.io/jkan/dashboard/ with the main sdg-indicators repository. That would be good. That way I do not have to recreate the working header (and footer if that will be needed).

Only questions are "how?" and "when?".

-
