### ISSUE TITLE
CSS for indicator status

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#528]
@philipashlock - I am working on fixing the gap mentioned in Jen’s email below.  But on my desktop screen, I do not have a gap. https://gsa.github.io/sdg-indicators/status/ 

Is this problem device specific?  

If I cannot duplicate the problem, I won’t be able to find a solution.

Any ideas?	 

![gap](https://user-images.githubusercontent.com/16124816/26936430-b3b1ede0-4c3c-11e7-8270-db839eecae4a.jpg)

**Comment by JenPark9** [comment]
The issue appears to be fixed now. Thank you!

-----Original Message-----
