### ISSUE TITLE
Reporting status at the indicator level - mockups

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#531]
![box-for-no-data-01](https://user-images.githubusercontent.com/16124816/27181320-19824b20-51a5-11e7-8ec9-2f176fc28efc.jpg)
Courtesy of Christopher Long.

**Comment by angela-smithers** [comment]
This first layout is a solution;
it sums up the issue all in one go,
it is a good size - the user won't need to scan the page any further in order to understand (hierarchy).

**Comment by angela-smithers** [comment]
![box-for-no-data-02](https://user-images.githubusercontent.com/16124816/27181402-81721828-51a5-11e7-96ed-9181e9629d6f.jpg)
![box-for-no-data-03](https://user-images.githubusercontent.com/16124816/27181405-838ef93c-51a5-11e7-8d2c-28093a2198d4.jpg)
![box-for-no-data-04](https://user-images.githubusercontent.com/16124816/27181406-85ff7624-51a5-11e7-849f-4e279171c608.jpg)

**Comment by angela-smithers** [comment]
The above images are other takes on the first idea

**Comment by cmterrylynn** [comment]
With Mock ups I can’t run all of my checks.  From what I can tell so far, the blue used for the tabs, and the gray when active, look a bit light in color, so just be sure the actual colors are ones we have been using or ping me with Hex numbers to run.  Be sure the links for “Download CSV” have mark up to indicate “Download CSV for Goal 1 Exploring Data” or something along that line that ensures a blind user knows what they downloaded data will represent.
Ensure the red badge around Exploring Data is one of our compliant ones.
Let me know as soon as you have a live page, and I’ll run the full test on it.

**Comment by angela-smithers** [comment]
Hello,
An example of the result can be seen here: https://gsa.github.io/sdg-indicators/8-7-1/

**Comment by JenPark9** [comment]
I think this looks good!

**Comment by cmterrylynn** [comment]
I’ll give it a 508 run this afternoon.  Looks great though!

Terry Lynn (TL) Sales
Section 508 and UI Tester
DHS/CBP/OIT/CSPD
571-468-5271 Desk
703-945-2777 B’Berry

**Comment by cmterrylynn** [comment]
The red used for the Exploring Data color badge is coming in at 4.0:1 where the requirement is 4.5:1 for color contrast where there is text.  Need to darken the red here.  If you click the Log/in log/out button, the page has a github log in screen.  There is a red button with white letters here that would be perfect to mimmick.
If the data table in the Metadata tab adds another column at some point, then we will need to do table markup, but for now it can be considered a simple layout table.

Terry Lynn (TL) Sales
Section 508 and UI Tester
DHS/CBP/OIT/CSPD
571-468-5271 Desk
703-945-2777 B’Berry
