### ISSUE TITLE
for Angela- FM-spa  training-forking resource matrix

### ISSUE THREAD

**Issue by Moris-OMB** [GSA/sdg-indicators#540]
Making Your Own National Reporting Platform 
Thinking about making your own version of this national reporting platform to report SDG statistics? These materials can help you get started. The US NRP is open source and free to copy (or “fork”).
•	US Quick Start Guide
•	Frequently Asked Questions
•	NRP intro deck and webinar
•	NRP forking description and webinar	

Desarrollando su propia plataforma nacional
Si esta planeando su propia versión de esta plataforma, estos materiales pueden ayudarle a comenzar. La plataforma nacional (NRP) de Objetivos de Desarrollo Sostenible  (ODS o SDG) de USA esta basado en un código abierto y gratuito, disponible para copiar.
 
USA Guía de inicio rápido
Preguntas frecuentes
Presentación y seminario web de introduction de el NRP
Descripción y seminario web de copiar el NRP

***

Customizing Your Platform 
Once you’ve copied your platform, here are some tips for customizing it to fit your needs.
•	Translating the NRP
•	Changing national graphics on the NRP 	

Personalización de la plataforma
Una vez que haya copiado su plataforma, aquí hay algunos consejos para personalizarla y adaptarla a sus necesidades.
 
Traducir el PNR
Cambio de gráficos nacionales en el PNR

***
Conducting a Data Needs Assessment 
Thinking about how to identify data gaps? These materials may be helpful.
•	US SDG Data Needs Survey
•	UNECE CES Survey of Data Needs for SDG 	

Evaluando las necesidades de datos
Pensando en cómo identificar algunos datos? Estos materiales pueden ser útiles.
 
US SDG Encuesta de Necesidades de Datos
UNECE CES Encuesta de necesidades de datos para SDG

***

Training Data Providers 
Here are some materials that may help train data providers to input statistics and metadata into your NRP.
•	NRP Data Provider Guide, training deck, and webinar

 	Capacitando proveedores de datos 
La siguiente informacion pueden ayudar a entrenar proveedores de datos y metadatos en su NRP.
 
Guía para proveedor de datos del NRP y seminario web

***

Road Maps for Reporting SDG Statistics 
Thinking about how to plan for reporting SDG statistics? These links may help.
•	UNECE CES Roadmap 	

Planes para generar informes de estadísticas de SDG
¿Pensando en cómo planear para reportar las estadísticas de SDG? Estos enlaces pueden ayudar.
Plan de la UNECE CES
Plan de el US SDG NRP

***

Have other questions about building your own NRP from our open source (free) model? Other questions or suggestions for our site? Contact us at sdgs@omb.eop.gov.

¿Tiene otras preguntas sobre como desarrollar su propio NRP desde nuestro modelo de código abierto (gratuito)? ¿Otras preguntas o sugerencias? Comuníquese con nosotros usando sdgs@omb.eop.gov.

**Comment by angela-smithers** [comment]
Thanks!  Entered pull request #542
