### ISSUE TITLE
Error message for indicator 8.a.1 on Github

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#587]
@philipashlock Dearest Phil (and/or Angela),
A data provider got an error message in Github.  She provided data last year, so, she isn’t new to this process.
Did she provide enough information for you to troubleshoot?  I don’t know if this is an isolated issue-- I only issued the data call this morning and she is the first one I’ve heard from.

Thanks for looking into this.

From: Kimberly 
Sent: Monday, September 18, 2017 3:48 PM
To: Kong, Kali 
Subject: Re: Data Call- 2017 U.S. Statistics for the UN SDGs (GREEN indicators)

Dear Kali,

I just tried to upload the data for my indicator, 8-a-1 on Github, and it is giving me an error message.  Could you please confirm the data was updated?  In the event that the data was not uploaded, it is attached for your reference.

Thanks,
Kim

**Comment by smithkimberj** [comment]
![image](https://user-images.githubusercontent.com/21341661/30562744-8eb9890c-9c8d-11e7-8c26-cb9166ad18ac.png)

**Comment by JenPark9** [comment]
If Phil can't check quickly, I will check when I get to my hotel.
I have to see if a pull request was generated.

Sent from my iPhone

On Sep 18, 2017, at 4:23 PM, smithkimberj <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<>https://user-images.githubusercontent.com/21341661/30562744-8eb9890c-9c8d-11e7-8c26-cb9166ad18ac.png<>

-

**Comment by JenPark9** [comment]
Kimberly needs to click on the lower green square at the bottom of the edit page. (When you haven't been in the system for a while, it prompts you to do this). Let her know? Ty!

Sent from my iPhone

On Sep 18, 2017, at 4:07 PM, Angela <notifications@github.com<mailto:notifications@github.com>> wrote:


@philipashlock<>https://github.com/philipashlock<> Dearest Phil (and/or Angela),
A data provider got an error message in Github. She provided data last year, so, she isn't new to this process.
Did she provide enough information for you to troubleshoot? I don't know if this is an isolated issue-- I only issued the data call this morning and she is the first one I've heard from.

Thanks for looking into this.

From: Kimberly
Sent: Monday, September 18, 2017 3:48 PM
To: Kong, Kali
Subject: Re: Data Call- 2017 U.S. Statistics for the UN SDGs (GREEN indicators)

Dear Kali,

I just tried to upload the data for my indicator, 8-a-1 on Github, and it is giving me an error message. Could you please confirm the data was updated? In the event that the data was not uploaded, it is attached for your reference.

Thanks,
Kim

-

**Comment by philipashlock** [comment]
This is covered on page 8 of the [training guide](https://gsa.github.io/sdg-indicators/assets/documents/Training%20Guide%20for%20DATA%20PROVIDERS_v1(no%20overview)%20(1).pdf) and is also listed under "Troubleshooting Common Data Entry Errors" on page 19, but maybe there's a way to emphasize this step or remind folks for this latest data call.
