### ISSUE TITLE
Update US NRP landing site and ribbon

### ISSUE THREAD

**Issue by JenPark9** [GSA/sdg-indicators#603]

**Comment by JenPark9** [comment]
Will send an email with snip. We want to add "FAQs" to the end of the ribbon. We also want to create a splash page for the user when they first arrive to the site that explains that this is the mechanism that the US is using to report on SDGs. Kali will develop content; can @angela-smithers develop graphics? We would want to include on staging site now and push to main site mid-October.

**Comment by JenPark9** [comment]
**Requesting US Statistics for the SDGs**
Looking for the most recent US statistics for the SDGs? You can find them on this site under US Statistics ` https://gsa.github.io/sdg-indicators/'. We typically update US statistics in the fall of each year; some updates are made a bit later to accommodate existing release schedules. The date of last update and anticipated next update appear in the indicator's national metadata page. Statistics and metadata can be downloaded in csv format.

**Guidance for UN custodian agencies requesting US data or national metadata for the SDGs**
Are you a UN custodian agency looking for official US statistics for the SDGs? Do you have a question regarding our national metadata? Are you requesting validation for harmoninzed global statistics? Contact us at US_Chief_Statistician@omb.eop.gov referencing the particular indicator and a proposed response date and we will route your question to our experts.
 
**Requesting US Comments on SDG Indicator Development**
Are you a UN custodian agency requesting US comments on SDG global indicator development? We have experts for those questions, too. Contact us at US_Chief_Statistician@omb.eop.gov referencing the particular indicator and a proposed response date and we will route your question to our experts.

**Developing methods for SDG indicator calculation?** 
Here’s how you can reach us. Contact us at US_Chief_Statistician@omb.eop.gov referencing the particular indicator/target and a proposed response date and we will route your question to our experts.

**Comment by JenPark9** [comment]
Angela, can you add the content above to the FAQ page? Thank you!

**Comment by JenPark9** [comment]
Hi Angela,
Just checking in on this one. Can you add this content for us to the FAQ page (see above)? Thanks!

**Comment by angela-smithers** [comment]
Hello, @JenPark9 @PhilipAshlock
Can you change the "assignee" to me? It makes it easier to find.

**Comment by angela-smithers** [comment]
update #749

**Comment by JenPark9** [comment]
Just assigned to you. Thank you!
