### ISSUE TITLE
graphics for updates to statistics on the NRP

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#605]
...a NRP "nice to have" request that is not urgent but would be very useful to manage our data calls as we update statistics on the NRP.

When we update a previously populated indicator (denoted in green as "reported online") by adding or altering statistics or any changes to metadata, I would like the NRP to show a star indicating that an update has been made. This could be triggered by a pull request or something else off the metadata.

Similarly, when an indicator changes status from "exploring data sources" to "statistics in progress" or "reported online" I would like the NRP to show the same star indicating that an update has been made.

Below are low-res drafts for review:

![artboard 1 copy](https://user-images.githubusercontent.com/16124816/30934671-46a39444-a39c-11e7-9b20-37f1a60d22f3.jpg)
![artboard 1 copy 2](https://user-images.githubusercontent.com/16124816/30934668-468467ae-a39c-11e7-9263-9fc717542ae3.jpg)
![artboard 1 copy 3](https://user-images.githubusercontent.com/16124816/30934670-46959d08-a39c-11e7-999a-6a4d740ef796.jpg)
![artboard 1 copy 4](https://user-images.githubusercontent.com/16124816/30934669-4685cc0c-a39c-11e7-9392-b16e98efb891.jpg)
![artboard 1 copy 5](https://user-images.githubusercontent.com/16124816/30934672-46b7ba14-a39c-11e7-8e3d-4cb186746fde.jpg)

@JenPark9  @philipashlock

**Comment by angela-smithers** [comment]
Click on the above images for a better view

**Comment by JenPark9** [comment]
I like options 4 and 5 best. Could we insert "updated!" in the star, or is that not possible?  Also, what would the 'i' denote? A change in status from red to green? Could we just use the star instead? Open to further thoughts/push back. Thanks, Angela!!

**Comment by henningsh** [comment]
I like the circle of arrows icon from the 1st option over the "i" in 4, but otherwise agree with Jen. The placement at the far left is nice. I like the simplicity of the icons, but appreciate how option 5 makes it clear the what the difference is. Maybe the icons could be used, but a legend added to the top of the page? Or would that be too cluttered?

I also like the idea though of just using one icon (star). Is it necessary to distinguish between "new" and "revised" data? That said, you'd want to be clear about what "new" means. Is it new as of that week? Month? Since some specific date?

**Comment by angela-smithers** [comment]
In lieu of a legend, we could add a tooltip on-click/on tap.

**Comment by JenPark9** [comment]
I like it!

Sent from my iPhone

On Sep 28, 2017, at 8:37 AM, Angela <notifications@github.com<mailto:notifications@github.com>> wrote:


In lieu of a legend, we could add a tooltip on-click/on tap.

-

**Comment by henningsh** [comment]
Me too!

**Comment by JenPark9** [comment]
I manually entered the update dates for the indicators that have been updated during this data call so far (17.6.2, 14.4.1, 9.4.1, 7.2.1, 7.3.1., and 8.a.1.). I used the format YYYY-MM-DD. Will continue to do this as pull requests are accepted and until we have a auto stamp available.

**Comment by angela-smithers** [comment]
Changes made for yellow star to meet Accessibility.  Tooltip added (nothing fancy), will most likely use the default Bootstrap CSS.
![initial layout-03](https://user-images.githubusercontent.com/16124816/31033364-b8e95a88-a52d-11e7-87af-2a2c15a0f9a8.PNG)
![initial layout-04](https://user-images.githubusercontent.com/16124816/31033365-b8eac29c-a52d-11e7-9772-ec697988ae6a.PNG)
![initial layout-05](https://user-images.githubusercontent.com/16124816/31033366-b8ee3940-a52d-11e7-946b-8d5b7310add2.PNG)

**Comment by angela-smithers** [comment]
Since IE 10+ is having trouble with webfonts (including Font Awesome), this would most likely be a PNG or SVG image

**Comment by JenPark9** [comment]
I love that there is a “font awesome”!

**Comment by JenPark9** [comment]
I like how "revised" fits in the rectangle, but I am concerned that the shape will confuse readers given the shape of the status icons. what if we drop the start and rectangle and just wrote in block letters new or revised? (Although, then we would need to code differently if the data, metadata or indicator were new or revised.) How about "updated"?

**Comment by angela-smithers** [comment]
I agree - too many rectangles ...

**Comment by angela-smithers** [comment]
For the label with the black back background we could use the same styling found here: https://gsa.github.io/sdg-indicators/status/
For the star with border and tooltip, I am attaching the PNG (SVG will be on Max.gov because it cannot be uploaded here).
![artboard 2](https://user-images.githubusercontent.com/16124816/31278930-003c3490-aa75-11e7-8376-7bac838c042d.png)

**Comment by JenPark9** [comment]
I like the star. The black background label would use something like

**Comment by JenPark9** [comment]
Please go ahead and mock up the black background label. :) Thank you!

**Comment by angela-smithers** [comment]
Going back to idea #5 
https://user-images.githubusercontent.com/16124816/30934672-46b7ba14-a39c-11e7-8e3d-4cb186746fde.jpg

**Comment by angela-smithers** [comment]
![update-badge-1](https://user-images.githubusercontent.com/16124816/31902770-0254cec2-b7f4-11e7-8d66-d5a41db3b9f3.png)
![update-badge-2](https://user-images.githubusercontent.com/16124816/31902773-042e9f2a-b7f4-11e7-8d10-ddf4d2176a50.png)

**Comment by angela-smithers** [comment]
Currently using the side-by-side badge option, but would like to revisit the popover/flag
Samples:
https://codepen.io/jasondavis/pen/mlnEe
https://codepen.io/macsupport/pen/OPwvwx
https://codepen.io/joshintosh/pen/fBqpo

Bootstrap CSS:
`.popover{position:absolute;top:0;left:0;z-index:1060;display:none;max-width:276px;padding:1px;font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:14px;font-style:normal;font-weight:400;line-height:1.42857143;text-align:left;text-align:start;text-decoration:none;text-shadow:none;text-transform:none;letter-spacing:normal;word-break:normal;word-spacing:normal;word-wrap:normal;white-space:normal;background-color:#fff;-webkit-background-clip:padding-box;background-clip:padding-box;border:1px solid #ccc;border:1px solid rgba(0,0,0,.2);border-radius:6px;-webkit-box-shadow:0 5px 10px rgba(0,0,0,.2);box-shadow:0 5px 10px rgba(0,0,0,.2);line-break:auto}.popover.top{margin-top:-10px}.popover.right{margin-left:10px}.popover.bottom{margin-top:10px}.popover.left{margin-left:-10px}.popover-title{padding:8px 14px;margin:0;font-size:14px;background-color:#f7f7f7;border-bottom:1px solid #ebebeb;border-radius:5px 5px 0 0}.popover-content{padding:9px 14px}.popover>.arrow,.popover>.arrow:after{position:absolute;display:block;width:0;height:0;border-color:transparent;border-style:solid}.popover>.arrow{border-width:11px}.popover>.arrow:after{content:"";border-width:10px}.popover.top>.arrow{bottom:-11px;left:50%;margin-left:-11px;border-top-color:#999;border-top-color:rgba(0,0,0,.25);border-bottom-width:0}.popover.top>.arrow:after{bottom:1px;margin-left:-10px;content:" ";border-top-color:#fff;border-bottom-width:0}.popover.right>.arrow{top:50%;left:-11px;margin-top:-11px;border-right-color:#999;border-right-color:rgba(0,0,0,.25);border-left-width:0}.popover.right>.arrow:after{bottom:-10px;left:1px;content:" ";border-right-color:#fff;border-left-width:0}.popover.bottom>.arrow{top:-11px;left:50%;margin-left:-11px;border-top-width:0;border-bottom-color:#999;border-bottom-color:rgba(0,0,0,.25)}.popover.bottom>.arrow:after{top:1px;margin-left:-10px;content:" ";border-top-width:0;border-bottom-color:#fff}.popover.left>.arrow{top:50%;right:-11px;margin-top:-11px;border-right-width:0;border-left-color:#999;border-left-color:rgba(0,0,0,.25)}.popover.left>.arrow:after{right:1px;bottom:-10px;content:" ";border-right-width:0;border-left-color:#fff}

<img src="{{ site.baseurl }}/assets/img/Artboard_2.png" /> `

**Comment by JenPark9** [comment]
I still like the star. :) @philipashlock do you have a better idea?

**Comment by philipashlock** [comment]
Sorry not to weigh in here more earlier. Another option could be to append the "Updated" badge to the end of the indicator name so we don't take up any extra width. For example: 

![screen shot 2017-10-23 at 4 39 27 pm](https://user-images.githubusercontent.com/183402/31912083-ce6043f4-b810-11e7-9aba-ca4d30acbc0f.png)

The problem with the star or other icons is that I don't think there's any symbol that's universally understood to mean what we want it to mean here, so then we're depending on the user having to figure out what it means. It does save space and looks nice visually, but I don't think it conveys meaning to anybody other than those who have been explicitly told what it means. I don't think clicking on it is very intuitive, but if this is the route we want to go perhaps giving the column headings a name, like "Recently Updated" will make it self explanatory enough if there's a star there. 

We can always do user testing to confirm what works best

**Comment by JenPark9** [comment]
That does align better, but maybe it looks like the indicator has been updated (in some cases, that's true), instead of the statistics/metadata being updated (that would be true in all intended flagged cases).
Taking votes from the team? And still like "Updated!" to show enthusiasm. :)

**Comment by philipashlock** [comment]
Another option could be that we have a column that lists the last updated date for all of them and then has styling to distinguish the ones that are **recently updated** like bold typeface or another color. This would avoid "wasting space" and provide some useful detail for all of them, but might also add to a bit of information overload. 

One thing we should consider is that if these flags are only for people closely involved with managing this project, as opposed to the general public, we might consider creating two separate versions of this table. One that might be more information dense or with less intuitive symbols and another version that is just stripped to the essentials for the general public.

**Comment by JenPark9** [comment]
I think we want to flag updates for everybody--that something has changed. And I think we just want one version at a very high level; the metadata page can have the particulars. 
Can Kali's solution work? Star ⭐️ = Updated!

**Comment by philipashlock** [comment]
Sure, let's go for a legend at the top of the page. One advantage that has over using column headings is that we could explain other symbols like "Revised Data" as well without creating another column for it.

**Comment by JenPark9** [comment]
Yay!

**Comment by angela-smithers** [comment]
A little lost.

1.  the star stays
2. the legend stays
3. the additional column to the left goes?
4. the star is now placed/inserted **after** the indicator description?

What if the star was at the front of the Indicator description? Would that work?
Am I redo-ing the code? Or is Phil coding the real thing that feeds off the new "date" row?

**Comment by JenPark9** [comment]
:) 
the star stays
the legend stays
the additional column to the left STAYS
the star is now placed/inserted just where it is. Thank you!

**Comment by JenPark9** [comment]
Hi @angela-smithers ,
Please add stars to 1.5.1 and 11.5.1 as well. Thank you!
Jen

**Comment by JenPark9** [comment]
Hi @angela-smithers and @Kali2017SDG ,
Also, please make sure that stars are added to these (maybe the last ones for this push):
3.a.1, 5.6.1, 14.5.1, 7.1.1

**Comment by Kali2017SDG** [comment]
It is 8.6.1 (not 5.6.1).
Thanks!

**Comment by JenPark9** [comment]
Yes, apologies. Sigh.
