### ISSUE TITLE
2017 Data Call Progress-Green Indicators Updated (updates may not yet be complete)

### ISSUE THREAD

**Issue by JenPark9** [GSA/sdg-indicators#667]
1-2-1
1-3-1
1-5-2
**3-1-2**^
**3-2-1**^
**3-2-2**^
3-3-1
3-3-2
3-3-4
**3-4-1**^
**3-4-2**^
3-5-2
**3-6-1**^
**3-7-1**^
**3-7-2**^
**3-9-3**^
**3-a-1** Updated 11/2
3-c-1
4-1-1
4-2-2
**4-3-1 ^ &**
**4-4-1 ^ &**
**4-5-1 ^ ? seems to be a problem graphing read4_total here** 
**4-6-1 ^ &**
**4-a-1 ^ &**
4-c-1
5-2-1 Updated 11/9
**5-4-1^**   *
5-5-2 
5-b-1
**6-1-1** Updated 11/1.
7-1-1
7-2-1
7-3-1
8-1-1
**8-2-1^**
8-4-2
**8-5-1 ^ % **  
**8-5-2 ^ % **
**8-6-1** updated 11/2
8-10-1
**8-10-2^ %**
8-a-1
9-1-2
9-2-1
9-4-1
9-5-1
**9-c-1** updated further on 11/2
10-1-1
10-4-1
11-1-1
11-5-2
11-6-2
12-2-2
13-1-1
14-4-1
**14-5-1^*** Added 2017 data; waiting to hear re 2000-2013
16.1.1 Updated 11/9/2017
16.2.2 Updated 11/9/2017
17.1.1
17-3-2
17.4.1
17-6-2
17-8-1
**17.18.3^
17.19.2^**
*still updating 2000-2006
**^updated after 10/23**
** & no new data anticipated for some time **
** % no older data are available.

**Comment by angela-smithers** [comment]
@philipashlock , I will manually insert the star image and tooltip beginning tomorrow unless you have something else tentatively in progress

**Comment by JenPark9** [comment]
Plus 8.2.1

**Comment by angela-smithers** [comment]
grabbing new updates, Update #757

**Comment by Kali2017SDG** [comment]
I forgot to bring this up earlier on the NRP call.
On list, I think there is a typo.  There isn't an indicator 7.7.1

**Comment by JenPark9** [comment]
Fixed to 7.1.1.
I also added to Angela’s code to put a star on 6.1.1. (Travis is just double checking now.)

**Comment by angela-smithers** [comment]
now changing 11.5.1
