### ISSUE TITLE
Translation syntax clarification - indicator.md

### ISSUE THREAD

**Issue by henningsh** [GSA/sdg-indicators#675]
I'm working on French translation for the sdg-indicators/_translations/indicator.md page and noticed the way the sentences are broken up between sections doesn't work with the required syntax for French.

The English reads ( "//" indicates breaks in the code):

"... Complete global //metadata documentation on all indicators in Goal 4//, unless otherwise noted, is provided by the UN Statistics Division." 

Accurate translation to French would be ( *....* highlights relevant clause):

"... *La documentation complète sur les métadonnées* de tous les indicateurs de l'Objectif 4//, sauf indication contraire, est fournie par la Division de statistique de l'ONU."

Note that "complete" has moved from being the initial word of the sentence to the third word. I'm unclear why the break in the code is placed precisely there, and am unsure how to duplicate in French. Two options would be to either:

"... La documentation //complète sur les métadonnées..." (The documentation //complete on the metadata ...)

or:

"...La documentation complète //sur les métadonnées..."  (The [complete] documentation //on the metadata ...)

Finally, note that "global" has dropped out of the translation into French. I'm unclear if "global" is modifying "documentation" as in "global documentation of metadata" or is modifying "metadata" as in "documentation of global metadata." Please advise which is the correct interpretation and I can update to reflect the change. Also, is "global" hear meaning "overall" or "worldwide"? Thanks!

**Comment by JenPark9** [comment]
See below in ALLCAPS. Thank you!

**Comment by henningsh** [comment]
Thanks Jen!
