### ISSUE TITLE
Graph for yes/no indicators

### ISSUE THREAD

**Issue by JenPark9** [GSA/sdg-indicators#722]
We will need a way to make indicators completed with yes/no values into "green, reported on line" and let the table be shown or something.  Examples are listed below for ease of reference.
13-1-1 
17.18.3
17.19.2

**Comment by philipashlock** [comment]
Should we just show the data table or is there some way we'd want to visualization the yes/no values over time? I don't know if there's any well established convention for displaying binary values like that in a time series, but we could attempt to do something like this using the existing graphing library:

![screen shot 2017-10-30 at 6 31 33 pm](https://user-images.githubusercontent.com/183402/32198892-928c964e-bda0-11e7-9726-09285e5651f3.png)

**Comment by henningsh** [comment]
It's certainly not an established convention, but Edward Tufte has a design he uses to illustrate win/loss records for sports. Could be another option -- up lines represent wins, down lines represent losses.

![capture](https://user-images.githubusercontent.com/31774570/32227937-18527604-be23-11e7-9f88-7b727cd8a3eb.PNG)

**Comment by JenPark9** [comment]
I think both of these are good. In general, for the SDGs, we can expect that once a no turns to a yes, it will remain a yes. (Typically, it is when a statute is issued.) Any ideas for a graphing situation where the image is a sideways h like this? ____|-----

**Comment by Kali2017SDG** [comment]
I can't seem to upload neither an excel file or .png

**Comment by JenPark9** [comment]
No, we can’t do that from our omb system. We can do that from a public system.
You can try inserting it in an email here, and perhaps Stephanie or Phil can load it.

**Comment by Kali2017SDG** [comment]
[cid:image001.jpg@01D35235.8F0CA030]

**Comment by JenPark9** [comment]
Nope, it didn’t work. Can you put it in a normal email (from your usual account at OMB) and send to Stephanie for loading?

**Comment by angela-smithers** [comment]
https://codepen.io/angela-smithers/pen/eeNemw
https://codepen.io/angela-smithers/pen/gXpXao

Working on a vertical example ... next

**Comment by angela-smithers** [comment]
... a diverging bar chart on it's side ...
with only two statuses ... http://blog.askia.com/wp-content/uploads/2016/03/Screenshot-2016-03-30-10.29.01.png

**Comment by JenPark9** [comment]
This is a sort of population pyramid type. There are four ordered response categories. So, this is not a great fit for the yes/no graph. But thank you for looking!

**Comment by philipashlock** [comment]
Great, I should be able to update the template with this approach later this afternoon.

**Comment by JenPark9** [comment]
Yes, that looks a bit like Stephanie's suggestion. Let's try--but with one color, right?

**Comment by philipashlock** [comment]
Yep. Here's roughly what I'll be implementing ([live example on jsfiddle](http://jsfiddle.net/jsarrwq5/4/))

![screen shot 2017-10-31 at 4 55 34 pm](https://user-images.githubusercontent.com/183402/32248582-79fc92c0-be5c-11e7-8671-eda659741377.png)

**Comment by philipashlock** [comment]
There's an initial version of this live now, but it does not yet support multivariate graphing. The indicators that have been updated so for (by adding a value to the `indicator_variable` field in the metadata) are:

* [13.1.1](https://gsa.github.io/sdg-indicators/13-1-1/)
* [17.18.2](https://gsa.github.io/sdg-indicators/17-18-2/)
* [17.18.3](https://gsa.github.io/sdg-indicators/17-18-3/)
* [17.19.2](https://gsa.github.io/sdg-indicators/17-19-2/)

**Comment by JenPark9** [comment]
Phil,
Thanks! I  am good w this solution. Ladies? Note Angela we would need stars inserted here. Kali, we will need to comb through red and some green indicators potentially to make sure that in cases where we have y:n responses we have signaled that the indicator is green, that a binary graph and indicator for graphing is identified, and the data table is shown. If you put a list of any such troublesome indicators in the issue thread, I think I can fix it on my end.

Sent from my iPhone

On Oct 31, 2017, at 6:37 PM, Philip Ashlock <notifications@github.com<mailto:notifications@github.com>> wrote:


There's an initial version of this live now, but it does not yet support multivariate graphing. The indicators that have been updated so for (by adding a value to the indicator_variable field in the metadata) are:

  *   13.1.1<>https://gsa.github.io/sdg-indicators/13-1-1/<>
  *   17.18.2<>https://gsa.github.io/sdg-indicators/17-18-2/<>
  *   17.18.3<>https://gsa.github.io/sdg-indicators/17-18-3/<>
  *   17.19.2<>https://gsa.github.io/sdg-indicators/17-19-2/<>

-

**Comment by Kali2017SDG** [comment]
I will do complete sweep through all indicators and prepare a list -- first thing in the morning.

Philip-- If you get a chance, please help with graph for indicator 17.4.1... blank graph ( because they completely changed indicators w/o notifying anyone in advance)
Jen- I sent that email out yesterday because I was not able to reach Andrew via phone (to ask if Dennis reviewed/approved).  I do not believe Andrew would be so bold as to do it himself.  I will try to call him again tomorrow and will call Scott if I can't reach him.  Lucky for him this fell in SDG17 (w/ no co-chair to annoy).

**Comment by Kali2017SDG** [comment]
Yes, the yes/no graphs look good.  The only thing is that it should be blue (Angela submitted a pull/push request earlier today)  Thanks, Philip.

**Comment by JenPark9** [comment]
☺
