### ISSUE TITLE
Icon to indicate "No updates expected"

### ISSUE THREAD

**Issue by Kali2017SDG** [GSA/sdg-indicators#743]
There are may be a dozen or so (e.g. SDG4 has four: 4.3.1, 4.4.1, 4.6.1 and 4.a.1) "green" indicators that depend on federal data with irregularly scheduled data releases.  

Can we use some sort of icon (non-yellow star) to depict this?   
Thanks!

**Comment by JenPark9** [comment]
The list of such indicators is in the issue “2017 Data Call Progress-Green Indicators Updated…” noted by & or %
