### ISSUE TITLE
Translate site disclaimer text and other elements

### ISSUE THREAD

**Issue by brockfanning** [GSA/sdg-indicators#822]
There are a couple of pieces of text that would benefit from translation, which would also simplify the forking guidance for countries. These are:

* This is a staging site used to update and preview indicator data
* This is an official website of the United States government

There are also a few random interface elements that could be translated:

* Login
* Logout
* Return to top
* Updated! (already have Spanish, just need French)
* [number] indicators (for example, "25 indicators")

I'm happy to make a pull request once I've got the translations, but I wasn't sure if there is a usual process for getting something translated.

**Comment by JenPark9** [comment]
Thank you, Brock. I believe Angela can initiate SPA translation and Larry can affirm it. Then, either Angela or you would be welcome to implement the changes. Assigning to Angela.

**Comment by angela-smithers** [comment]
😳🤔😬
I can list the translations but it may be faster to let you know ... all I do is use translate.google.com

**Comment by brockfanning** [comment]
@angela-smithers Gotcha, no need then. I'll submit a PR. :)

**Comment by brockfanning** [comment]
Pull request submitted: #829
