### ISSUE TITLE
Translate short versions of goals to Spanish

### ISSUE THREAD

**Issue by brockfanning** [GSA/sdg-indicators#824]
The short versions of goals still need to be translated to Spanish. They are:

* No Poverty
* Zero Hunger
* Good Health and Well-being
* Quality Education
* Gender Equality
* Clean water and sanitation
* Affordable and clean energy
* Decent jobs and economic growth
* Industry, innovation and infrastructure
* Reduced inequalities
* Sustainable Cities & Communities
* Responsible consumption and production
* Climate action
* Life below water
* Life on land
* Peace and justice - strong institutions
* Partnerships for the goals

I'm happy to make a pull request once I have the translations.

**Comment by JenPark9** [comment]
Thank you, Brock. These may be available on the UNSD or UN website on SDGs as official translations. I am assigning to Angela in case she can find them for you.

**Comment by angela-smithers** [comment]
If these are sourced from the .csv then I can see about creating a duplicate for Spanish by this Saturday if that’s alright. Just paste the link of the English file below so I know that I am duplicating the correct one

**Comment by angela-smithers** [comment]
But for the translations I would just look at the icons from the UN that were approved translations.
I don’t believe the short names are in the same file with the indicator names.

**Comment by brockfanning** [comment]
@angela-smithers I'm fine to copy from the icons. I'll submit a pull request soon.

**Comment by brockfanning** [comment]
Pull request submitted - #831
