### ISSUE TITLE
Update icon for Goal 10

### ISSUE THREAD

**Issue by brockfanning** [GSA/sdg-indicators#888]
Thanks @AnnCorp for this info: The icon for goal 10 needs to be updated. See here:
https://github.com/datasciencecampus/sdg-indicators/issues/2326

**Comment by brockfanning** [comment]
@AnnCorp Do you happen to know if there are Spanish versions available?

**Comment by AnnCorp** [comment]
Hi @brockfanning it says in this link that Spanish is one of the 6 official languages, so think they should be available:
http://www.un.org/sustainabledevelopment/news/communications-material/

**Comment by SmithersA** [comment]
Repeating the link information ... https://www.un.org/sustainabledevelopment/es/news/communications-material/ for Spanish.
Closing ticket.
