### ISSUE TITLE
Translate Reporting Status

### ISSUE THREAD

**Issue by SmithersA** [GSA/sdg-indicators#908]
sdg-indicators/fr/reporting-status.md is showing in Spanish

**Comment by SmithersA** [comment]
is this file needed? cannot find English equivalent

**Comment by SmithersA** [comment]
@audrey-a , Could you help with the French for the link that Brock posted above? You may have seen my terrible email version.

**Comment by audrey-a** [comment]
@SmithersA - can this be imported from the short column in the other csv
that I updated last week?



--
Audrey Ariss
Director of Research & Design, Center for Open Data Enterprise
<http://www.opendataenterprise.org>
m: +1 917-680-2416 | skype: audrey.aaa

**Comment by SmithersA** [comment]
Hello, @audrey-a I'm not sure. I have been trying to think up ways to tackle that csv

@brockfanning - any ideas? we cannot download the csv from GitHub to make changes (I don't see a button for that).  How can each csv be duplicated from the 'en' to the 'fr' folder so that we can edit it directly in the GitHub interface?

**Comment by brockfanning** [comment]
@audrey-a Looks like only the full names got translated to French, and the short names are still in Spanish.

**Comment by audrey-a** [comment]
I updated the French ones last week but can do so again if needed.



--
Audrey Ariss
Director of Research & Design, Center for Open Data Enterprise
<http://www.opendataenterprise.org>
m: +1 917-680-2416 | skype: audrey.aaa

**Comment by audrey-a** [comment]
Updated!



--
Audrey Ariss
Director of Research & Design, Center for Open Data Enterprise
<http://www.opendataenterprise.org>
m: +1 917-680-2416 | skype: audrey.aaa
