### ISSUE TITLE
Translate FAQ

### ISSUE THREAD

**Issue by SmithersA** [GSA/sdg-indicators#909]
sdg-indicators/fr/faq.md 

going to paste a Google translation in for now.
@audrey-a , could you please double-check it?

**Comment by SmithersA** [comment]
Cette page fournit des conseils sur l'accès ou la contribution aux données Américaines pour les SDG.

Demande de données Américaines pour les SDG

Vous recherchez les statistiques Américaines les plus récentes pour les SDG? Vous pouvez les trouver sur ce site sous US Statistics https://gsa.github.io/sdg-indicators/. Nous mettons généralement à jour les statistiques Américaines à l'automne de chaque année. Certaines mises à jour sont faites un peu plus tard pour s'adapter aux calendriers de diffusion existants. La date de la dernière mise à jour et la prochaine mise à jour prévue apparaissent dans la page des métadonnées nationales de l'indicateur. Les statistiques et les métadonnées peuvent être téléchargées au format CSV.

Guide pour les agences dépositaires des Nations Unies qui demandent des données Américaines ou des métadonnées nationales pour les SDG

Êtes-vous une agence dépositaire des Nations Unies à la recherche de statistiques officielles Américaines pour les SDG? Avez-vous une question concernant nos métadonnées nationales? Demandez-vous la validation pour des statistiques globales harmonisées? Contactez-nous à US_Chief_Statistician@omb.eop.gov en faisant référence à l'indicateur en question et à une date de réponse proposée. Nous acheminerons votre question à nos experts.

Demande de commentaires des États-Unis sur le développement de l'indicateur des SDG

Êtes-vous une agence dépositaire des Nations Unies qui demande des commentaires des États-Unis sur le développement d'indicateurs mondiaux des SDG? Nous avons aussi des experts pour ces questions. Contactez-nous à US_Chief_Statistician@omb.eop.gov en faisant référence à l'indicateur en question et à une date de réponse proposée. Nous acheminerons votre question à nos experts.

Développer des méthodes pour le calcul des indicateurs SDG?

Voici comment vous pouvez nous atteindre. Contactez-nous à US_Chief_Statistician@omb.eop.gov en vous référant à l'indicateur / cible particulier et à la date de réponse proposée. Nous acheminerons votre question à nos experts.

**Comment by brockfanning** [comment]
Pinging @audrey-a

**Comment by audrey-a** [comment]
Will take a look, can you send the US page being translated? 

I suggest updating references to the US to  'États-Unis' throughout (rather than 'Américain/e/s')

**Comment by SmithersA** [comment]
@audrey-a , better?
@brockfanning - this page is not rendering the updates https://sdg.data.gov/fr/faq/ yet

**Comment by audrey-a** [comment]
@smithers where can I find this French version on github?



--
Audrey Ariss
Director of Research & Design, Center for Open Data Enterprise
<http://www.opendataenterprise.org>
m: +1 917-680-2416 | skype: audrey.aaa

**Comment by SmithersA** [comment]
hello, @audrey-a  sdg-indicators/fr/faq.md
