### ISSUE TITLE
Pull in French images

### ISSUE THREAD

**Issue by SmithersA** [GSA/sdg-indicators#911]
Getting the icons from the established UN media materials.
https://www.un.org/sustainabledevelopment/fr/news/communications-material/

Will the sizes need to be optimized?  I cannot remember the pixel size that we agreed on.

**Comment by SmithersA** [comment]
renaming the images to match the current naming convention

**Comment by SmithersA** [comment]
Although the communication materials are labeled as 'web files', all the images are in CMYK - not web based. Should someone tell the UN team this??
The current dimensions for the French files are 3000px * 3000px at 300ppi

**Comment by SmithersA** [comment]
converted, optimized and uploaded French SDG icons into *new* coordinating folder

**Comment by SmithersA** [comment]
creating/converting for b&w

**Comment by brockfanning** [comment]
@SmithersA Those seem great to me. Note I changed the file names in #921 and also see [here](https://github.com/GSA/sdg-indicators/issues/917#issuecomment-387702769) for one more missing image.
