### ISSUE TITLE
Data file(s)

### ISSUE THREAD

**Issue by SmithersA** [GSA/sdg-indicators#914]
@brockfanning Does the French translation need the following file?
sdg-indicators/data/es/sdg_goals.csv

If yes, re-assign to me and I can duplicate the file. 
If so, does the Spanish version need to be finished also? Only goals 1 - 7 are translated.

**Comment by brockfanning** [comment]
@SmithersA Yes, I believe, to both questions.

**Comment by SmithersA** [comment]
https://github.com/GSA/sdg-indicators/blob/gh-pages/data/fr/sdg_goals.csv
Column 3 remains to be translated 
and sdg_indicator_metadata.csv remains to be created in https://github.com/GSA/sdg-indicators/blob/gh-pages/data/fr/

**Comment by philipashlock** [comment]
I'm closing this as a duplicate of #915
