### ISSUE TITLE
French translation of indicator metadata

### ISSUE THREAD

**Issue by SmithersA** [GSA/sdg-indicators#915]
There is a PDF packet published by the UN with all the goals and indicator titles translated into French. Will need that for the following:
https://github.com/GSA/sdg-indicators/tree/gh-pages/_goals
https://github.com/GSA/sdg-indicators/tree/gh-pages/_indicators
https://github.com/GSA/sdg-indicators/tree/gh-pages/data

Could it be emailed to me or attached below?

**Comment by SmithersA** [comment]
[E_CN-3_2017_2-FR(1).pdf](https://github.com/GSA/sdg-indicators/files/1985503/E_CN-3_2017_2-FR.1.pdf)

**Comment by SmithersA** [comment]
created "fr" folder in the link above,
started adding goals

**Comment by SmithersA** [comment]
@audrey-a , @brockfanning  - can't find the short French titles for this file sdg-indicators/data/fr/sdg_goals.csv
Could Audrey help with this? @OpenDataEnterprise

**Comment by SmithersA** [comment]
@brockfanning @philipashlock  - wasn't a French metadata csv file completed and emailed in 2017?

**Comment by SmithersA** [comment]
@audrey-a @Kali2017SDG  - should the word "Goal" be changed to "Objectif"?

**Comment by brockfanning** [comment]
@SmithersA About the French metadata CSV, I don't have anything - though I wasn't involved before November.

**Comment by SmithersA** [comment]
wow, that's a lot of work then - copy & paste

**Comment by audrey-a** [comment]
Yes - 'Objectif' is right



--
Audrey Ariss
Director of Research & Design, Center for Open Data Enterprise
<http://www.opendataenterprise.org>
m: +1 917-680-2416 | skype: audrey.aaa

**Comment by audrey-a** [comment]
Possibly, where is the file located?



--
Audrey Ariss
Director of Research & Design, Center for Open Data Enterprise
<http://www.opendataenterprise.org>
m: +1 917-680-2416 | skype: audrey.aaa

**Comment by SmithersA** [comment]
@audrey-a  good question ... I don't have the original csv anymore. What I can do is download the English one from this repo and email it to you. I cannot recall at the moment where the 'short goal titles' can be found.

**Comment by SmithersA** [comment]
email the draft version of goals. the English equivalent is here [sdg-indicators/data/sdg_goals.csv](url)

I think the Indicators will be the most tedious one

**Comment by audrey-a** [comment]
@SmithersA It might be easier to update the indicators from this csv https://unstats.un.org/sdgs/indicators/database/?area=FRA

**Comment by philipashlock** [comment]
To summarize, we need to create a copy of sdg_indicator_metadata.csv in french which should be located here: https://github.com/GSA/sdg-indicators/tree/gh-pages/data/fr/sdg_indicator_metadata.csv

Once that's created, we can use this script to generated the markdown files:
https://github.com/GSA/sdg-nrp-scripts/blob/master/sdg-indicators-metadata-translate.php

Here's an example of the spreadsheet we use for Spanish:
https://github.com/GSA/sdg-indicators/blob/gh-pages/data/es/sdg_indicator_metadata.csv

Here's an example of the spreadsheet we use for English:
https://github.com/GSA/sdg-indicators/blob/gh-pages/data/sdg_indicator_metadata.csv

**Comment by philipashlock** [comment]
It looks like we can use this spreadsheet: https://unstats.un.org/sdgs/indicators/Global%20Indicator%20Framework%20after%20refinement.French.xlsx

**Comment by SmithersA** [comment]
tackling the not so fun part: pasting in translations for https://github.com/GSA/sdg-indicators/blob/gh-pages/data/fr/sdg_indicator_metadata.csv

**Comment by SmithersA** [comment]
Next:
Will need to create French version of all the .md files here --> https://github.com/GSA/sdg-indicators/tree/gh-pages/_indicators/fr
