### ISSUE TITLE
statistics.md

### ISSUE THREAD

**Issue by SmithersA** [GSA/sdg-indicators#917]
@brockfanning - https://gsa.github.io/sdg-indicators/fr/statistics/ page does not render images ... the broken links are in Spanish when using the inspect tool

**Comment by brockfanning** [comment]
@SmithersA I've submitted a pull-request that fixes the goal image names: #921 

There's still one missing image though: /sdg-indicators/assets/img/fr/fr-sdg-goals-logo.png

Here's what the Spanish version looks like:
![Spanish SDG goal logo](https://gsa.github.io/sdg-indicators/assets/img/es/es-sdg-goals-logo.png)

**Comment by SmithersA** [comment]
Okay - will have this by end of day Thursday. I believe I have to convert it from CMYK to RGB and optimize it.

**Comment by SmithersA** [comment]
@brockfanning - the image is now uploaded but this is what I see :: 
![screen shot 2018-05-10 at 1 31 02 pm](https://user-images.githubusercontent.com/34685983/39883988-69dfb81e-5456-11e8-99ec-59522e4b36f0.png)

**Comment by brockfanning** [comment]
@SmithersA I think those images will be broken until #921 is merged.
