### ISSUE TITLE
Clicking on the French goal icons

### ISSUE THREAD

**Issue by SmithersA** [GSA/sdg-indicators#929]
![screen shot 2018-06-01 at 9 25 02 am](https://user-images.githubusercontent.com/34685983/40843151-158a9e8a-657e-11e8-867d-d0a5ab7247fe.png)
Clicking on any of the above icons produces a 404 error.
@brockfanning

**Comment by brockfanning** [comment]
@SmithersA Good catch - it looks like that might be happening with Spanish too?

**Comment by brockfanning** [comment]
It looks like the front page is coded to "slugify" the goal's translated shortname, and use that as the link. But the actual goal pages all use the English slug for their permalink. We'll need to either translate the slugified short names, or enforce the use of English slugs in the front page links. The latter is probably easier and more consistent with the rest of the platform.

**Comment by philipashlock** [comment]
We just need to generate the md files for french using the spreadsheet and the script, e.g. https://github.com/GSA/sdg-nrp-scripts/blob/master/sdg-indicators-metadata-translate.php

**Comment by philipashlock** [comment]
@SmithersA Sorry if I got mixed up, but do we have a spreadsheet of French translations for the indicator metadata already prepared? 

Here's an example of the two spreadsheets we use for Spanish: 
https://github.com/GSA/sdg-indicators/tree/gh-pages/data/es

But for French, I only see a spreadsheet for the goals, not the indicators: 
https://github.com/GSA/sdg-indicators/tree/gh-pages/data/fr

**Comment by philipashlock** [comment]
I posted that last comment in the wrong issue. @SmithersA, if you there are any updates to share you can add them to #915
